parser:
  \.pug$: "@markuplint/pug-parser"
extends:
  - "./markuplint-config/index.js"
  - "markuplint:recommended"
# nodeRules:
#   - selector: "script[src^='https://']"
#     rules:
#       required-attr: "Loading external resources is not allowed."

